### ISSUE TITLE
Figure out billing for SAI launched codespaces

### ISSUE THREAD

**Issue by grey-lovelace** [sourceallies/interviews#1]
- codespaces launched in this repo by users in the SAI team would bill to SAI instead of individual user
- codespaces launched NOT by SAI team member would bill to their own account
- Configure automatic deletion of codespaces launched from this repo for a certain amount of time

**Comment by tim-hornback-SAI** [comment]
Modifying codespace ownership requires org-level permissions.  In order to modify this setting, the org needs to subscribe to a not-free plan.  Our initial discussion decided that 120 core-hours per individual account should be more than sufficient for our use-case, and we could look into having overage-hours comped in some way (this has not been discussed or approved, just a thought for now).
